#!/usr/bin/env bash
# Regenerates THIRD_PARTY_NOTICES.md from the Rust crates linked into the prebuilt binaries.
set -euo pipefail
cd "$(dirname "$0")/.."
BIN=${CARGO_HOME:-$HOME/.cargo}/bin
RUSTC=$("$BIN/rustup" which rustc)
export RUSTC
CARGO=$("$BIN/rustup" which cargo)
REG=$(ls -d "${CARGO_HOME:-$HOME/.cargo}"/registry/src/*/ | head -1)
CRATES=$(cd rust && $CARGO tree -e normal,no-proc-macro --prefix none --format "{p}|{l}" --target aarch64-linux-android \
  | sed 's/ (\*)//' | grep -v '^hermes_intl ' | sort -u)
{
  echo "# Third-party notices"
  echo
  echo "The prebuilt binaries in \`prebuilt/\` contain the following Rust crates, most of them part of"
  echo "[ICU4X](https://github.com/unicode-org/icu4x). Generated by \`scripts/notices.sh\`."
  echo
  echo "| Crate | Version | License |"
  echo "| --- | --- | --- |"
  echo "$CRATES" | awk -F'|' '{split($1, a, " v"); printf "| %s | %s | %s |\n", a[1], a[2], $2}'
  echo
  echo "## Unicode License v3 (ICU4X and its data)"
  echo
  echo '```'
  head -60 "$REG"/icu_locale_core-2.3.*/LICENSE
  echo '```'
  # Crates under another license: their own license text (the MIT or Boost option when dual-licensed).
  echo "$CRATES" | grep -v '|Unicode-3.0$' | while IFS='|' read -r crate license; do
    name=${crate% v*}
    version=${crate##* v}
    dir="$REG/$name-$version"
    for f in LICENSE-MIT LICENSE-BOOST LICENSE LICENSE.txt LICENSE-APACHE; do
      if [ -f "$dir/$f" ]; then
        printf '\n## %s %s (%s)\n\n```\n' "$name" "$version" "$license"
        cat "$dir/$f"
        echo '```'
        break
      fi
    done
  done
} > THIRD_PARTY_NOTICES.md
